microservices/openmicroservices.org

capabilities/README.md

Just a small update because there was some disconnect between capabilities and capacities here.

Update erroneous capacities references

---

cli/test/README.md
commands/README.md

Removed entrypoint

---

cli/test/README.md
cli/validate/README.md

Fixes https://github.com/microservices/omg-cli/issues/104

Fix exec command to match omg

---

.vuepress/components/Explanation.vue
.vuepress/components/Supporters.vue
schema/actions/README.md
schema/environment/README.md
schema/events/README.md
schema/interface/README.md
schema/metrics/README.md

- Adding `The Twelve-Factor Microservice`
- Update various docs

The Twelve-Factor Microservice

---

.vuepress/fonts.styl
.vuepress/home.styl
.vuepress/style.styl

fix: header picture + fonts

---

_redirects

Fixes https://github.com/microservices/microservice.guide/issues/67

Fix #67 - add redirect for /cli

---

cli/test/README.md
cli/validate/README.md

- CLI:Validate: no --json by default
- CLI: microservice.guide -> microservice.yml
- CLI: omg exec has been renamed to omg run

A few small improvements

---

schema/authentication/README.md
schema/health/README.md
schema/logs/README.md
schema/metrics/README.md
schema/requirements/README.md

health, logs, requirements, metrics, authentication

refactor: add badges on multiple future features

---

introduction/anatomy/README.md
schema/health/README.md

Update based on new feature from OMG
See https://github.com/microservices/omg/pull/206

Update Health Checks

---

.gitignore
schema/health/README.md

Add note on what's considered healthy what's not. The service **MUST** return a 2xx HTTP code to be considered healthy

refactor(health): add precision on healthy requirements

---

examples/http/pubsub/README.md

Fix location of help.

---

schema/actions/README.md

Add support for sending objects in action arguments.

---

.vuepress/config.js
interoperability/openapi/README.md

Document openapi2omg fields.

---

.vuepress/components/Community.vue
.vuepress/components/pages/community/Libraries.vue
.vuepress/components/pages/home/OMGApp.vue
.vuepress/components/pages/home/OMGSpec.vue

- Adding missing OMG button links.
- Removing Slack section from Community page.

Update: Final QA

---

schema/actions/README.md

This should help bringing OMG and Storyscript closer together. I tried to model them after the existing OMG style. Feedback welcome.

Allow typed list + objects in OMG arguments

---

.vuepress/components/pages/community/Header.vue
.vuepress/components/pages/community/Repositories.vue
.vuepress/components/pages/home/Header.vue
.vuepress/components/pages/home/OMGSpec.vue
.vuepress/components/pages/home/Partners.vue
.vuepress/components/shared/OMGLogo.vue

* Correct all misspellings on landing pages.
* Prevent header logo text from line breaking incorrectly.

Correct misspellings & header text line breaks

---

schema/actions/README.md

Use 'output.type: none' for consistency

---

cli/overview/README.md
cli/test/README.md
cli/validate/README.md

Update oms install instructions

---

.vuepress/components/pages/home/Header.vue

[contributing guidelines](https://github.com/microservices/.github/blob/master/CONTRIBUTING.md)?
---
`API's` shouldn't be pluralized.

fix(homepage): correct grammatical error in homepage subtitle

---

app/.vuepress/config.js
package.json
yarn.lock

---
I've added a Vuepress plugin that generates a `sitemap.xml` during the `vuepress build` step.
Fixes #112

feat(seo): generate a sitemap.xml during the vuepress build step

---

app/schema/interface/README.md

---
Replaced `<SBadge ... />` with `<Badge ... />`, but not entirely sure why this fixes the problem, and why `SBadge` exists in the first place.
Fixes #143

fix(badges): replace custom badge component with native badge component

---

.gitignore
app/.vuepress/components/pages/about/TwelveFactors.vue
app/.vuepress/components/pages/community/Libraries.vue
app/cli/overview/README.md
app/examples/http/README.md
app/examples/http/pubsub/README.md
app/interoperability/openapi/README.md
app/introduction/anatomy/README.md
app/introduction/overview/README.md
app/schema/forwards/README.md
app/schema/metrics/README.md

---
Replacing outdated references to `microservice.yml` with `oms.yml`.

docs(oms.yml): replace references to `microservice.yml` with `oms.yml`

---

.github/README.md

---
> Note: Begins to resolve #151 - but the docs themselves should indeed reference that project and other implementations. 
Adding a table of example implementations to the README.
My hope is to give newcomers an easy-starting point, see some examples, and get a sense that the community is active.

docs(readme): add table of example implementations

---

app/schema/actions/README.md
app/schema/environment/README.md
app/schema/events/README.md
app/schema/health/README.md

Fixes https://github.com/microservices/microservice.guide/issues/57

Introduced 'deprecated' for actions, events, arguments and object properties

---

.all-contributorsrc

---
See https://github.com/microservices/openmicroservices.org/issues/169

chore: add default config for 'all contributors'

---

.all-contributorsrc

---
Add missing values to default all-contributors bot config.

chore: add missing fields to all contributors config

---

app/.vuepress/components/pages/home/OMSApp.vue
app/.vuepress/components/pages/home/OMSSpec.vue
app/.vuepress/components/shared/Contact.vue
app/.vuepress/components/shared/OMSLogo.vue
package.json

---
Minor updates to copy and contact information.
These are rolling changes, just wanted to flag a few things before revisiting in full.

chore: update copy

---

app/.vuepress/config.js
app/readme.md
package.json
yarn.lock

---
This PR adds the [vuepress `autometa`](//github.com/webmasterish/vuepress-plugin-autometa) plugin to the codebase.
I added a small openmicroservices.org configuration that can be easily edited and maintained in the future.
:sparkles: :wine_glass: 
---
**resolves #192**

feat(autometa): add vuepress autometa plugin and configuration

---

app/.vuepress/public/_redirects

From [netlify update](https://community.netlify.com/t/changes-coming-to-netlify-site-urls/8918) that is soon to be live, we need to force the redirections in the `_redirects` file

chore(netlify): update _redirects on netlify recommendations
